#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SPRING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  application:
    name: hexagonaldemo-ticket-api
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/ticket?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: hexagonaldemo-ticket-api
      max-lifetime: 2000000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SPRING CLOUD
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          auto-create-topics: false
          brokers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
      bindings:
        ticketReservedOutput:
          destination: ticketReserved.test.topic
        paymentRollbackOutput:
          destination: paymentRollback.test.topic

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# INFRA
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

server:
  port: 8094

kafka:
  enabled: true

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ADAPTERS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

administration:
  enabled: true
commandhandler:
  enabled: true
adapters:
  payment:
    enabled: true
    retryAttempts: 3
    retryDelay: 1
    baseUrl: http://${PAYMENT_API_HOST:localhost}:8090
    paymentPath: /api/v1/payments
  account:
    enabled: true