version: '3.6'

services:

  mysql:
    image: mysql
    container_name: hexagonaldemo_mysql
    volumes:
      - ./docs/ddl:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      LANG: C.UTF-8
    ports:
      - 3306:3306

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redisPassword
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  paymentapi:
    image: lemiorhan/hexagonaldemo-paymentapi:latest
    ports:
      - 8090:8090
    depends_on:
      - mysql
      - kafka
      - zookeeper
    environment:
      - DB_HOST=mysql
      - KAFKA_BROKER_HOST=kafka
      - REDIS_HOST=redis
    restart: on-failure

  ticketapi:
    image: lemiorhan/hexagonaldemo-ticketapi:latest
    ports:
      - 8094:8094
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - paymentapi
    environment:
      - DB_HOST=mysql
      - KAFKA_BROKER_HOST=kafka
      - PAYMENT_API_BASE_URL=paymentapi
      - REDIS_HOST=redis
    restart: on-failure

volumes:
  mysql_data:
    external:
      name: hexagonaldemo_mysql_data

networks:
  default:
    external:
      name: hexagonaldemo_network