name: Acceptance Test

on:
  push:
    paths:
      - ticket-api/**
      - payment-api/**
      - acceptance-test-suite/**
      - .github/workflows/acceptance-test.yml
      - run-acceptance-tests.sh
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create API's And Run Tests
        run: |
          docker volume create hexagonaldemo_mysql_data
          echo "volume created"
          docker network create hexagonaldemo_network
          echo "network created"
          docker-compose -f docker-compose-ci.yml up -d
          echo "Running acceptance test has started"
          ./gradlew clean :acceptance-test-suite:cucumber -PskipInfraSetup -Dorg.gradle.daemon=false
          echo "Running acceptance test has finished"