name: Payment API Run Build On Each Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - payment-api/**
      - .github/workflows/payment-api*.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 4306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build
        run: |
          ./gradlew verifierStubsJar :payment-api:build -PskipInfraSetup -Dorg.gradle.daemon=false
