name: Build Payment API Image

on:
  push:
    paths:
      - payment-api/**
      - .github/workflows/payment-api*.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 4306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build
        run: |
          ./gradlew verifierStubsJar :payment-api:build :payment-api:bootJar -PskipInfraSetup -Dorg.gradle.daemon=false

      - name: Upload Jar File
        uses: actions/upload-artifact@v1
        with:
          name: payment-api-jar
          path: payment-api/build/libs