name: testing

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    services:

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 4306:3306
