name: test workflow

on:
  push:
    paths:
      - ticket-api/**
      - ticket-api/Dockerfile
      - .github/workflows/test-workflow.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build
        run: |
          ./gradlew :ticket-api:build :ticket-api:bootJar -PskipInfraSetup -Dorg.gradle.daemon=false -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          dockerfile: ./ticket-api/Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ticket-api
          push: true
          tags: lemiorhan/hexagonaldemo-ticketapi:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}