name: testing

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    services:

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 4306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Init Database
        run:  mysql -uroot -h127.0.0.1 --port 4306 --password=my-secret-pw -e 'CREATE DATABASE IF NOT EXISTS db1;'
