name: testing

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    services:

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 4306:3306

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Init Database
        run:  mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS db1;'
